# Project
version=2.0.0
group=com.christofmeg.mifa
java_version=21

# Mod options
minecraft_version=1.21.1
mod_name=More Industrial Foregoing Addons
mod_author=Christofmeg
mod_id=mifa
license=The MIT License (MIT)
description=This mod adds additional efficiency, processing and speed addons to Industrial Foregoing.
catalogueItemIcon=mifa:speed_addon_3
minecraft_version_range=[1.21, 1.22)

# Fabric | https://fabricmc.net/develop/
fabric_minecraft_version=1.21
fabric_supported_versions=1.21.x
fabric_version=0.100.3+1.21
fabric_loader_version=0.15.11

# Forge | https://files.minecraftforge.net/net/minecraftforge/forge/
forge_minecraft_version=1.21
forge_supported_versions=1.21.x
forge_version=51.0.31
forge_loader_version_range=[0,)
forge_version_range=[0,)

# NeoForge | https://projects.neoforged.net/neoforged/neoforge
neoforge_minecraft_version=1.21.1
neoforge_supported_versions=1.21.x
neoforge_version=21.1.119
neoforge_loader_version_range=[4,)
neoforge_minecraft_version_range=[1.21,1.22)

# Quilt | https://lambdaurora.dev/tools/import_quilt.html
quilt_minecraft_version=1.21
quilt_supported_versions=1.21.x
quilt_version=11.0.0-alpha.3+0.100.7
quilt_loader_version=0.26.0

# Parchment | https://parchmentmc.org/docs/getting-started
parchment_mc=1.21.1
parchment_version=2024.11.17

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# CurseForgeGradle | Minotaur options
cf_id=1086142
modrinth_id=Ig6QciUH
release_type=release
neoforge_release_versions=1.21,1.21.1
